<?php 
// RAMIFIP PHP FRAMEWORK - Generated file - 2013-07-29 09:26:22 - PHP Configuration file
v("autouse",array());
v("pkg_links",array());
v("paths",array());
v("event_paths",array());
v("router_paths",array());
v('router_paths|index',array());
v('router_paths|file',array());
v('router_paths|img',array());
v('router_paths|js',array());
v('router_paths|css',array());
v('router_paths|xml',array());
v("use",array());
v('packages|objectdb', array('id' => 'objectdb', 'type' => 'package', 'name' => 'ObjectDB', 'group' => '', 'version' => '4.1', 'path' => 'packages/com/pragres/objectdb/objectDB.package', 'dependences' => array(), 'js' => array(), 'css' => array()));
v('autouse|IODBConnection', 'com/pragres/objectdb/lib/IODBConnection');
v('autouse|ODBConnectionPgSQL', 'com/pragres/objectdb/drivers/ODBConnectionPgSQL');
v('autouse|ODBConnectionMySQL', 'com/pragres/objectdb/drivers/ODBConnectionMySQL');
v('autouse|ODBConnectionMSSQL', 'com/pragres/objectdb/drivers/ODBConnectionMySQL');
v('autouse|ODBException', 'com/pragres/objectdb/lib/ODBException');
v('autouse|ODBConnection', 'com/pragres/objectdb/lib/ODBConnection');
v('autouse|ODBObject', 'com/pragres/objectdb/lib/ODBObject');
v('autouse|objectDB', 'com/pragres/objectdb/lib/objectDB');
v('packages|lesscss', array('id' => 'lesscss', 'type' => 'package', 'name' => 'LESS CSS parser', 'group' => 'Ramifip Core 3rdParty Libs', 'version' => '1.3.0', 'path' => 'packages/ramifip/lib/3rdParty/lesscss/lesscss.package', 'dependences' => array(), 'js' => array("0" => "ramifip/lib/3rdParty/lesscss/less"), 'css' => array()));
v('autouse|lessc', 'ramifip/lib/3rdParty/lesscss/lessc');
v('packages|div', array('id' => 'div', 'type' => 'package', 'name' => 'Div, PHP Template Engine', 'group' => 'PHP Template Engine', 'version' => '1.0', 'path' => 'packages/ramifip/lib/div/div.package', 'dependences' => array(), 'js' => array(), 'css' => array()));
v('autouse|div', 'ramifip/lib/div/div');
v('packages|rpAjax', array('id' => 'rpAjax', 'type' => 'package', 'name' => 'Ramifip AJAX', 'group' => 'Ramifip RIA', 'version' => '1.0', 'path' => 'packages/ramifip/modules/rpAjax/rpAjax.package', 'dependences' => array(), 'js' => array("0" => "ramifip/modules/rpAjax/rpAjax"), 'css' => array("0" => "ramifip/modules/rpAjax/rpAjax")));
v('packages|rpCore', array('id' => 'rpCore', 'type' => 'package', 'name' => '', 'group' => 'Ramifip', 'version' => '1.0', 'path' => 'packages/ramifip/modules/rpCore/rpCore.package', 'dependences' => array(), 'js' => array(), 'css' => array()));
v('packages|rpDBDriver', array('id' => 'rpDBDriver', 'type' => 'package', 'name' => '', 'group' => '', 'version' => '1.0', 'path' => 'packages/ramifip/modules/rpDBDriver/rpDBDriver.package', 'dependences' => array(), 'js' => array(), 'css' => array()));
v('autouse|rpDBDriver', 'ramifip/modules/rpDBDriver/rpDBDriver');
v('autouse|rpDBDriverMySQL', 'ramifip/modules/rpDBDriver/rpDBDriverMySQL');
v('autouse|rpDBDriverPostgreSQL', 'ramifip/modules/rpDBDriver/rpDBDriverPostgreSQL');
v('packages|rpHelper', array('id' => 'rpHelper', 'type' => 'package', 'name' => '', 'group' => '', 'version' => '1.0', 'path' => 'packages/ramifip/modules/rpHelper/rpHelper.package', 'dependences' => array(), 'js' => array(), 'css' => array()));
v('autouse|rpHelperHTML', 'ramifip/modules/rpHelper/rpHelperHTML');
v('packages|rpJSGUI', array('id' => 'rpJSGUI', 'type' => 'package', 'name' => 'Ramifip Javascript GUI', 'group' => 'Ramifip RIA', 'version' => '1.0', 'path' => 'packages/ramifip/modules/rpJSGUI/rpJSGUI.package', 'dependences' => array("jquery-ui" => "jquery-ui"), 'js' => array("0" => "ramifip/modules/rpJSGUI/rpJSGUI", "1" => "ramifip/modules/rpJSGUI/rpJSGUI.window", "2" => "ramifip/modules/rpJSGUI/rpJSGUI.tabs", "3" => "ramifip/modules/rpJSGUI/rpJSGUI.overlay", "4" => "ramifip/modules/rpJSGUI/rpJSGUI.modalframe", "5" => "ramifip/modules/rpJSGUI/rpJSGUI.notification", "6" => "ramifip/modules/rpJSGUI/rpJSGUI.checkBoxList", "7" => "ramifip/modules/rpJSGUI/rpJSGUI.input", "8" => "ramifip/modules/rpJSGUI/rpJSGUI.fieldsetCollapsible", "9" => "ramifip/modules/rpJSGUI/rpJSGUI.validateFields", "10" => "ramifip/modules/rpJSGUI/rpJSGUI.grids", "11" => "ramifip/modules/rpJSGUI/rpJSGUI.checkBoxGrid", "12" => "ramifip/modules/rpJSGUI/rpJSGUI.fileChooser", "13" => "ramifip/modules/rpJSGUI/rpJSGUI.remoteExplorer"), 'css' => array("0" => "ramifip/modules/rpJSGUI/rpJSGUI")));
v('packages|rpORM', array('id' => 'rpORM', 'type' => 'module', 'name' => 'Ramifip ORM for PHP', 'group' => '', 'version' => '1.0', 'path' => 'packages/ramifip/modules/rpORM/rpORM.package', 'dependences' => array("rpDBDriver" => "rpDBDriver"), 'js' => array(), 'css' => array()));
v('autouse|rpDataCollection', 'ramifip/modules/rpORM/rpDataCollection');
v('autouse|rpDataAccess', 'ramifip/modules/rpORM/rpDataAccess');
v('autouse|rpDataTable', 'ramifip/modules/rpORM/rpDataTable');
v('autouse|rpDataTrigger', 'ramifip/modules/rpORM/rpDataTrigger');
v('autouse|rpEntity', 'ramifip/modules/rpORM/rpEntity');
v('autouse|rpORM', 'ramifip/modules/rpORM/rpORM');
v('packages|rpTranslator', array('id' => 'rpTranslator', 'type' => 'module', 'name' => 'Ramifip Translator', 'group' => 'i18n', 'version' => '1.0', 'path' => 'packages/ramifip/modules/rpTranslator/rpTranslator.package', 'dependences' => array(), 'js' => array(), 'css' => array()));
v('use|rpTranslator', 'ramifip/modules/rpTranslator/rpTranslator');
v('packages|ramifip', array('id' => 'ramifip', 'type' => 'package', 'name' => 'Ramifip Framework Core Package', 'group' => 'Ramifip Core', 'version' => '1.0', 'path' => 'packages/ramifip/ramifip.package', 'dependences' => array(), 'js' => array(), 'css' => array()));
v('packages|recipes-admin', array('id' => 'recipes-admin', 'type' => 'application', 'name' => 'Mirta\'s Recipes Administration', 'group' => '', 'version' => '1.0', 'path' => 'packages/recipes/admin/recipes.admin.package', 'dependences' => array(), 'js' => array("0" => "admin>> com/nicEdit/nicEdit", "1" => "admin>> com/jquery/jquery-ui-i18n"), 'css' => array("0" => "admin>> recipes/admin/recipes.admin")));
v('entry|admin|download/subscribelist','recipes/admin/events/subscribelist');
v('entry|admin|download/recipes','recipes/admin/events/recipeslist');
v('packages|51f716466ee0e', array('id' => '51f716466ee0e', 'type' => 'package', 'name' => '', 'group' => '', 'version' => '1.0', 'path' => 'packages/recipes/common/model/Recipes.package', 'dependences' => array(), 'js' => array(), 'css' => array()));
v('autouse|diet', 'recipes/common/model/diet');
v('autouse|foodtype', 'recipes/common/model/foodtype');
v('autouse|horary', 'recipes/common/model/horary');
v('autouse|horary_recipe', 'recipes/common/model/horary_recipe');
v('autouse|ingredient', 'recipes/common/model/ingredient');
v('autouse|ingredient_recipe', 'recipes/common/model/ingredient_recipe');
v('autouse|nationality', 'recipes/common/model/nationality');
v('autouse|occasion', 'recipes/common/model/occasion');
v('autouse|preparationtype', 'recipes/common/model/preparationtype');
v('autouse|recipe', 'recipes/common/model/recipe');
v('autouse|secretsofcooking', 'recipes/common/model/secretsofcooking');
v('autouse|subscribe', 'recipes/common/model/subscribe');
v('autouse|usercomments', 'recipes/common/model/usercomments');
v('packages|recipes-common', array('id' => 'recipes-common', 'type' => 'package', 'name' => '', 'group' => '', 'version' => '1.0', 'path' => 'packages/recipes/common/recipes.common.package', 'dependences' => array(), 'js' => array("0" => "recipes/common/recipes"), 'css' => array()));
v('autouse|RecipesModel', 'recipes/common/RecipesModel');
v('autouse|RecipePDF', 'recipes/common/RecipePDF');
v('autouse|PDF', 'recipes/common/PDF');
v('autouse|RecipesControl', 'recipes/common/RecipesControl');
v('packages|recipes-portal', array('id' => 'recipes-portal', 'type' => 'application', 'name' => 'Mirta\'s Recipes Cookbook Page', 'group' => '', 'version' => '1.0', 'path' => 'packages/recipes/portal/recipes.portal.package', 'dependences' => array(), 'js' => array("0" => ">> ../packages/com/dynamicdrive/multizoom/multizoom"), 'css' => array("0" => ">> recipes/portal/recipes.portal","1" => ">> ../packages/com/dynamicdrive/multizoom/multizoom")));
v('paths|download', 'download/SaveRecipe.php');
v('router_paths|file|download','download/SaveRecipe.php');
v('paths|images/recipes', '../files/recipes');
v('router_paths|img|images/recipes','../files/recipes');
v('packages|recipes', array('id' => 'recipes', 'type' => 'project', 'name' => 'Mirta\'s Recipes', 'group' => '', 'version' => '1.0', 'path' => 'packages/recipes/recipes.package', 'dependences' => array(), 'js' => array("0" => "com/jquery/jquery-ui"), 'css' => array("0" => "recipes/recipes","1" => "com/jquery/themes/base/jquery.ui.all","2" => "com/jquery/themes/smoothness/ui.all")));
v('scripts|cron', 'Recipes Cron'); 
v('paths|sitemap.xml', 'recipes/portal/sitemap.xml.php');
v('router_paths|xml|sitemap.xml','recipes/portal/sitemap.xml.php');
v('paths|admin', 'Recipes\'s Administration');
v('paths|images', 'recipes/portal/images');
v('router_paths|img|images','recipes/portal/images');
v('paths|admin/graphs', 'recipes/admin/view/graphs');
v('router_paths|img|admin/graphs','recipes/admin/view/graphs');
